- name: Generate docker-compose.yml file and copy it
  template:
    src: docker-compose.yml.j2
    dest: "{{ USER_PATH }}/docker-compose.yml"
  tags: docker, docker-compose

- name: Append a line to docker file to store temps in disk
  lineinfile:
    path: /etc/default/docker
    line: export DOCKER_TMPDIR="{{ STORAGE }}/docker-tmp"
    insertafter: EOF

- name: Add my user to Docker
  command: "sudo usermod -a -G docker {{ USER }}"
  tags: docker

- name: Stop Docker
  command: sudo docker-compose down
  tags: docker, docker-compose

- name: Start Docker
  command: sudo docker-compose up -d
  environment: 
    COMPOSE_HTTP_TIMEOUT: "180"
  tags: docker, docker-compose

# ZSH
- name: Install Oh My Zsh
  become_user: "{{ USER }}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    clone: yes
  tags: packages, zsh

- name: Generate zshrc file and copy it
  become_user: "{{ USER }}"
  template:
    src: zshrc.j2
    dest: "~/.zshrc"
  tags: packages, zsh

- name: Install Powerlevel10k theme
  become_user: "{{ USER }}"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
  tags: packages, zsh

- name: Set Zsh as default shell
  become: true
  shell: chsh -s "$(which zsh)" {{ USER }}
  tags: packages, zsh