- name: Copy aliases
  copy: 
    src=.bash_aliases 
    dest="{{ USER_PATH }}/.bash_aliases"
  tags: aliases

- name: Append disks config to fstab
  become: true
  blockinfile:
    path: /etc/fstab
    block: |
      {% for drive in DRIVES %}
      UUID={{ drive.UUID }} {{ drive.MOUNT }} {{ drive.FS }} defaults 0 0
      {% endfor %}
    state: present
    create: yes
    insertafter: EOF
  tags: mount-disk

- name: Mount disks
  become: true
  command: mount -a
  tags: mount-disk