- name: Copy aliases
  copy: 
    src=.bash_aliases 
    dest="{{ USER_PATH }}/.bash_aliases"
  tags: environment, aliases

- name: Generate telegram_notification_disk.sh file and copy it
  template:
    src: telegram_notification_disk.sh
    dest: "{{ USER_PATH }}/scripts/cron/telegram_notification_disk.sh"
    owner: root
    group: root
    mode: '0755'
  tags: environment, cron

- name: Create cron job for telegram_notification_disk.sh
  cron:
    name: "Disk space check"
    minute: "30"
    hour: "4"
    job: "{{ USER_PATH }}/scripts/cron/telegram_notification_disk.sh > /dev/null 2>&1"
  tags: environment, cron

- name: Generate telegram_notification_argument.sh file and copy it
  template:
    src: telegram_notification_argument.sh
    dest: "{{ USER_PATH }}/scripts/telegram_notification_argument.sh"
    owner: root
    group: root
    mode: '0755'
  tags: environment, telegram

- name: Reconfigure default DNS configuration #Otherwise Pi-hole won't start
  block:
  - name: Stop systemd-resolved service
    systemd:
      name: systemd-resolved
      state: stopped
      enabled: no

  - name: Remove the /etc/resolv.conf symlink
    file:
      path: /etc/resolv.conf
      state: absent
      force: yes

  - name: Create a new resolv.conf file
    copy:
      dest: /etc/resolv.conf
      content: |
        nameserver 127.0.0.1  # Local Docker DNS server
        nameserver 1.1.1.1    # CloudFlare Public DNS
        nameserver 8.8.8.8    # Google Public DNS (backup)
      owner: root
      group: root
      mode: '0644'

  tags: dns