- name: Copy aliases
  copy: 
    src=.bash_aliases 
    dest="{{ USER_PATH }}/.bash_aliases"
  tags: aliases

- name: Generate telegram_notification_disk.sh file and copy it
  template:
    src: telegram_notification_disk.sh
    dest: "{{ USER_PATH }}/scripts/cron/telegram_notification_disk.sh"
    owner: root
    group: root
    mode: '0755'
  tags: cron

- name: Create cron job for telegram_notification_disk.sh
  cron:
    name: "Disk space check"
    minute: "30"
    hour: "4"
    job: "{{ USER_PATH }}/scripts/cron/telegram_notification_disk.sh > /dev/null 2>&1"
  tags: cron

- name: Generate telegram_notification_argument.sh file and copy it
  template:
    src: telegram_notification_argument.sh
    dest: "{{ USER_PATH }}/scripts/telegram_notification_argument.sh"
    owner: root
    group: root
    mode: '0755'
  tags: telegram