- name: Include common variables
  include_vars:
    file: "{{ playbook_dir }}/roles/common/vars/main.yml"
    
- name: Update apt cache and upgrade all packages
  apt: 
    update_cache: yes
    upgrade: dist
  tags: installation, upgrade, packages

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - curl
    - zsh
    - git
    - bat
    - btop
    - apt-transport-https
    - ca-certificates
    - ntfs-3g
    - nfs-common
    - gnupg2
    - fail2ban
    - software-properties-common
    - python3-venv
  tags: installation, packages

# ctop
- name: Install docker-ctop
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64
    dest: /usr/local/bin/ctop
    mode: '0755'
  tags: installation, ctop

# Docker
- name: Install Docker
  become: true
  block:
    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        
    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker's apt repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      args:
        executable: /bin/bash

    - name: Update apt package index again (with Docker repo)
      apt:
        update_cache: yes
        
    - name: Add my user to Docker
      command: "sudo usermod -a -G docker {{ USER }}"

  tags: docker

- name: Install Docker and related packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  tags: dockertest

# ZSH
- name: Install Oh My Zsh and setup
  block:
    - name: Install Oh My Zsh
      become_user: "{{ USER }}"
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        clone: yes

    - name: Create directory for Powerlevel10k
      file:
        path: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
        state: directory
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: '0755'

    - name: Download Powerlevel10k
      become_user: "{{ USER }}"
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Generate zshrc file and copy it
      become_user: "{{ USER }}"
      template:
        src: zshrc
        dest: "~/.zshrc"

    - name: Set Zsh as default shell
      become: true
      shell: chsh -s "$(which zsh)" {{ USER }}

  tags: zsh